Add EditorConfig file
codecov/codecov-ruby pull request #107
Opened 2020-11-17 13:01 UTC by AlexWayfer

More info here: https://editorconfig.org/

Also fix some line-end spaces, file-end newlines.

2020-12-09 16:37 UTC, thomasrockhu requested changes
Will approve pending nit

2020-12-09 16:37 UTC, thomasrockhu commented on .editorconfig
> +insert_final_newline = true
Can these be alphabetized?

2020-12-10 02:42 UTC, thomasrockhu commented on .editorconfig
> +insert_final_newline = true
```suggestion
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true
```

2020-12-12 13:43 UTC, AlexWayfer commented on .editorconfig
> +insert_final_newline = true
Of course, if you want to. Suggested code has been accepted.

2020-12-12 15:14 UTC, thomasrockhu approved these changes

2020-12-12 15:14 UTC, merged